### PR TITLE
Add Right to Left option

### PR DESCRIPTION
**Pull request by marlowpayne**
Status: **Ready for Review**
Reviewers: @donnielrt 

Re-opening these changes as they are used by eXtra Stores' site.

## Changes
- Adds a right-to-left option 

## Todos:
- [x] +1

### Feedback:
_none so far_

## How to Test
- Checkout the code
- Experiment with setting the new `rightToLeft` option

### CODE REVIEW

**Comment by haroldtreen** [comment]
Could we add user facing documentation for this new feature? :)

Is there a project that would be easy to test this with? Should I clone eXtra, install old scooch, verify no option, update to this branch and verify the option works?

**Comment by marlowpayne** [comment]
@haroldtreen I'll update the README. eXtra is a good project for this feature, since it has an Arabic version.

**Comment by haroldtreen** [comment]
Sweet. I'll clone that repo and give this new magic a whirl.

**Comment by haroldtreen** [comment]
Looks good! :+1: 
Thanks @marlowpayne ! :smile:

**Comment by marlowpayne** [comment]
Woot! Thanks @haroldtreen :shipit:

**Comment by jansepar** [comment]
Zomg. Such SLA. Much merge. Wow.

**Pull request merged**
