### PR TITLE
Add a Right to Left option

### PR DESCRIPTION
**Pull request by marlowpayne**
Add an option for RTL cases
  
**Status**: *Opened for visibility*
 
**Reviewers**: @scalvert @donnielrt @ericmuyser @tedtate @kpeatt 
**Linked PRs**: https://github.com/mobify/scooch/pull/26
  
## Changes
- Added a RTL flag option: `rightToLeft` (defaults to false) for sites that use a right-to-left layout (e.g. eXtra Stores)
- When enabled, this option reverses how Scooch determines next and previous slide movements on dragging interactions
- Currently on eXtra Stores' build, grunt-css-flip handles the RTL inverting of the Scooch controls. We could possibly extend `rightToLeft` flag's functionality to perform these control changes Scooch-side. 

## How to test-drive this PR
- Pull down this change
- Init a new Scooch with `rightToLeft` option set to true: `$scooch.scooch({rightToLeft: true});`
- Check whether dragging in a left-to-right manner advances Scooch, and returns to previous slide on a right-to-left dragging interaction

## Note
- These changes are stacked on top of @ericmuyser 's fix for logic to auto-hide arrows

### CODE REVIEW

**Comment by ericmuyser** [comment]
Code looks good.

**Comment by ry5n** [comment]
bump?

**Comment by scalvert** [comment]
@ry5n do you need this? One thing we're doing is trying not to add anything to scooch before it's rewritten. If you need it sooner we can look at this.

**Comment by ry5n** [comment]
@scalvert We don’t need it for a project; we have something in place for EX already.

**Comment by donnielrt** [comment]
Hey, we’re looking to prune older unattended PRs. If this PR is still relevant and you would like to see it merged in, please reopen the PR and we’ll add it to our backlog! Thanks!

**Pull request closed without merging**
