### PR TITLE
FireFox missing images fix - text-align-center removed

### PR DESCRIPTION
**Pull request by nastiatikk**
Status: **In progress**
Reviewers: @tedtate @donnielrt @fractaltheory

## Changes
So this issue happens because of `m-center {text-align: center;}`. If I remove this class from `m-scooch` nothing happens. I don't know why it was originally used so I decided do not touch it and removed just the property that affects images performance. But if you think it's ok to remove this class we can do it. 

## GH Tickets:
- https://github.com/mobify/scooch/issues/30

## Todos:
- [ ] Engineer +1
- [ ] Designer +1

## How to Test

### CODE REVIEW

**Comment by nastiatikk** [comment]
@noahadams I see it was your styles. Is `m-center` required class?

**Comment by ericmuyser** [comment]
Can't you remove the `m-center` class from your HTML instead of removing the CSS in the plugin? 

BTW `build/scooch.min.js` should be changing if `src/scooch.js` didn't change.

**Comment by nastiatikk** [comment]
@ericmuyser it's not a project fix, but scooch fix in FireFox browser regarding the issue #30.
And I was also surprised why `js` file was changed if I never opened it.

**Comment by tedtate** [comment]
Removing `m-center` is not a good solution as it does have an affect on appearance.

m-center enabled

m-center disabled

We need to look into why `text-align: center` is causing a breakage on firefox.

**Comment by ericmuyser** [comment]
I agree with Ted. A slightly better solution would be to reset the `text-align` with an FF only selector.

**Comment by cdegit** [comment]
After investigating this issue, I've developed an alternate fix: https://github.com/mobify/scooch/pull/33

**Comment by donnielrt** [comment]
Hey, we’re looking to prune older abandoned PRs. If this PR is still relevant and you would like to see it merged in, please reopen the PR and we’ll add it to our backlog! Thanks!

**Pull request closed without merging**
